/* eslint-disable react/react-in-jsx-scope */
// INFO: all svg icons will go below
import React from 'react';
import {Info} from './image/svgIcons/IcInfo';
import {EyeClose} from './image/svgIcons/IcEyeClose';
import {EyeOpen} from './image/svgIcons/IcEyeOpen';
import {ForwardArrow} from './image/svgIcons/IcForwardArrow';
import {BackWardArrow} from './image/svgIcons/IcBackwardArrow';
import {Mail} from './image/svgIcons/IcMail';
import {Phone} from './image/svgIcons/IcPhone';
import {Share} from './image/svgIcons/IcShare';
import {RightArrow} from './image/svgIcons/IcRightArrow';
import {Home} from './image/svgIcons/IcHome';
import {Profile} from './image/svgIcons/IcProfile';
import {Meetings} from './image/svgIcons/IcMeetings';
import {OneToOne} from './image/svgIcons/IcOneToOne';
import {Scanner} from './image/svgIcons/IcScanner';
import {Events} from './image/svgIcons/IcEvents';
import {Cross} from './image/svgIcons/IcCross';
import {Edit} from './image/svgIcons/IcEdit';
import {Key} from './image/svgIcons/IcKey';
import {Seat} from './image/svgIcons/IcSeat';
import {AddImage} from './image/svgIcons/IcAddImage';
import {Plus} from './image/svgIcons/IcPlus';
import {Search} from './image/svgIcons/IcSearch';
import {Check} from './image/svgIcons/IcCheck';
import {Glob} from './image/svgIcons//IcGlob';
import {Location} from './image/svgIcons/IcLocations';
import {Clock} from './image/svgIcons/IcClock';
import {DressCode} from './image/svgIcons/IcDressCode';
import {Attendance} from './image/svgIcons/IcAttendance';
import {QR} from './image/svgIcons/IcQR';
import {Minus} from './image/svgIcons/IcMinus';
import {Trash} from './image/svgIcons/IcTrash';
import {Settings} from './image/svgIcons/IcSettings';
import {Flame} from './image/svgIcons/IcFlame';
import { ProductCart } from './image/svgIcons/IcProduct';

export const IcInfo = props => <Info {...props} />;
export const IcFlame = props => <Flame {...props} />;
export const IcProductCart = props => <ProductCart {...props} />;
export const IcEyeClose = props => <EyeClose {...props} />;
export const IcEyeOpen = props => <EyeOpen {...props} />;
export const IcForwardArrow = props => <ForwardArrow {...props} />;
export const IcCheck = props => <Check {...props} />;
export const IcBackArrow = props => <BackWardArrow {...props} />;
export const IcMail = props => <Mail {...props} />;
export const IcPhone = props => <Phone {...props} />;
export const IcShare = props => <Share {...props} />;
export const IcTrash = props => <Trash {...props} />;
export const IcRightArrow = props => <RightArrow {...props} />;
export const IcSettings = props => <Settings {...props} />;
export const IcHome = props => <Home {...props} />;
export const IcProfile = props => <Profile {...props} />;
export const IcMeetings = props => <Meetings {...props} />;
export const IcOneToOne = props => <OneToOne {...props} />;
export const IcScanner = props => <Scanner {...props} />;
export const IcEvents = props => <Events {...props} />;
export const IcCross = props => <Cross {...props} />;
export const IcEdit = props => <Edit {...props} />;
export const IcKey = props => <Key {...props} />;
export const IcSeat = props => <Seat {...props} />;
export const IcAddImage = props => <AddImage {...props} />;
export const IcPlus = props => <Plus {...props} />;
export const IcSearch = props => <Search {...props} />;
export const IcGlob = props => <Glob {...props} />;
export const IcLocation = props => <Location {...props} />;
export const IcClock = props => <Clock {...props} />;
export const IcDressCode = props => <DressCode {...props} />;
export const IcAttendance = props => <Attendance {...props} />;
export const IcQR = props => <QR {...props} />;
export const IcMinus = props => <Minus {...props} />;
